# fly.toml app configuration file generated for jazzbuckets on 2026-08-26T19:45:46-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jazzbuckets'
primary_region = 'dfw'

[build]
[env]
  BUCKETS_DB_PATH = '/data/buckets.db'
  BUCKETS_SECURE_COOKIES = '1'

[[mounts]]
  source = 'buckets_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
